Repository LavergneC/mega-bataille-navale, pull requests merged in 2020-03, with the labels that each got.

#112 111 mise a jour carte adversaire
  src/carte.py
  src/jeu.py
  tests/test_carte.py
Labels: Backend, Ready for merge, bug

#113 90 creer thread
  .travis.yml
  src/jeu.py
  src/qml/Page_connexion/Connexion_Window.qml
  tests/test_jeu.py
Labels: Backend, Ready for merge

#116 111 mise a jour carte adversaire
  src/carte.py
  src/jeu.py
  src/navire.py
  src/qml/Attaque/CaseAtt.qml
  src/qml/Page_connexion/Rejoindre.qml
Labels: Backend, bug

#119 better attaque shot display
  src/jeu.py
  src/navire.py
  src/qml/Attaque/CaseAtt.qml
Labels: GUI, Ready for merge, bug, enhancement

#120 118 ajout indicateur bateau coule
  src/carte.py
  src/caseattaque.py
  src/jeu.py
  src/qml/Attaque/CaseAtt.qml
  tests/test_carte.py
Labels: Backend, GUI, Ready for merge, enhancement
