Repository LavergneC/mega-bataille-navale, pull requests merged in 2020-02, with the labels that each got.

#24 Modification index dans recevoir_tir
  src/jeu.py
Labels: bug

#25 Modifcation moment d'incrémentation de l'index de l'étage dans recevoir_tir
  src/jeu.py
Labels: Ready for merge, bug

#14 Actualisation de l'état des cases
  src/carte.py
  src/case.py
  src/navire.py
Labels: work in progress

#27 Fix test_impact tests
  tests/test_navire.py
Labels: bug

#30 Add Pyside2 dependancy + cover tested code
  .coveralls.yml
  .travis.yml
  README.md
  requirements.txt
Labels: bug, work in progress

#22 lien qml python
  src/jeu.py
  src/main.py
  src/qml/Attaque/CarteAttaque.qml
  src/qml/Attaque/CaseAtt.qml
  src/qml/Defense/CarteDefense.qml
  src/qml/Defense/CaseDef.qml
  src/qml/main.qml
Labels: Ready for merge, enhancement

#28 Vertical swipe carte defence
  src/jeu.py
  src/main.py
  src/qml/Defense/CarteDefense.qml
  src/qml/Defense/CustomPageIndicator.qml
  src/qml/main.qml
Labels: Ready for merge, enhancement

#35 Création de la page de connexion
  src/qml/Images/attention.svg
  src/qml/Images/bateau.jpg
  src/qml/Images/bonneinfo.svg
  src/qml/Images/fondecran1.jpg
  src/qml/Images/fondecran1.jpg.xmp
  src/qml/Images/fondecran2.jpg
  src/qml/Images/fondecran3.jpg
  src/qml/Images/fondecranbataillenavale.JPG
  src/qml/Images/images-removebg-preview.png
  src/qml/Images/mauvaiseinfo.svg
  src/qml/Images/mer.jpg
  src/qml/Page_connexion/Connexion_Window.qml
  src/qml/Page_connexion/Heberger.qml
  src/qml/Page_connexion/Indication_Connexion.qml
  src/qml/Page_connexion/Ma_popup.qml
  src/qml/Page_connexion/Rejoindre.qml
  src/qml/main.qml
Labels: GUI, Ready for merge

#37 ajout deuxième bateau au niveau 2 et whataformer
  src/jeu.py
  src/navire.py
  tests/test_jeu.py
Labels: Backend, Ready for merge, documentation, enhancement

#38 new QML archi
  src/qml/Defense/CarteDefense.qml
  src/qml/Jeu.qml
  src/qml/Page_connexion/Connexion_Window.qml
  src/qml/main.qml
Labels: GUI, Ready for merge, invalid

#41 Add pytest-cov packet
  .travis.yml
  requirements.txt
Labels: enhancement, work in progress

#46 Ajout id pour les navires
  src/navire.py
  tests/test_carte.py
  tests/test_jeu.py
  tests/test_navire.py
Labels: Backend, Ready for merge, bug

#47 rename Jeu_qml
  src/qml/Partie.qml
  src/qml/main.qml
Labels: GUI, Ready for merge, bug

#42 34 ajout documentation
  src/carte.py
  src/case.py
  src/jeu.py
  src/navire.py
Labels: Backend, Ready for merge, documentation

#39 5 positionnement des navires
  src/carte.py
  src/jeu.py
  src/navire.py
  tests/test_carte.py
  tests/test_jeu.py
  tests/test_navire.py
Labels: Backend, Ready for merge, enhancement

#48 Add flake8 linter for src and tests code
  .travis.yml
  requirements.txt
  src/navire.py
Labels: Ready for merge, enhancement

#50 49 resolution des avertissements linter
  .travis.yml
  src/carte.py
  src/jeu.py
  src/navire.py
  tests/test_carte.py
  tests/test_jeu.py
  tests/test_navire.py
Labels: Backend, enhancement, work in progress

#55 Change the check_ship method and add new method to update case state
  src/carte.py
  tests/test_carte.py
Labels: Backend, Ready for merge, bug

#56 51 redaction de tests plus pousses
  src/carte.py
  tests/test_carte.py
  tests/test_navire.py
Labels: Backend, Ready for merge

#57 45 ajout partie reseau
  src/jeu.py
  src/reseau.py
  tests/test_carte.py
Labels: Backend, enhancement, work in progress

#60 Call mise_a_jour_case method
  src/jeu.py
  tests/test_carte.py
Labels: Backend, bug, work in progress

#63 Ajout du choix du nom dans la page de connexion
  src/qml/Page_connexion/Connexion_Window.qml
Labels: GUI, Ready for merge, bug

#62 Handle shoot_anwser in parse_message
  src/jeu.py
  tests/test_jeu.py
Labels: Backend, enhancement, work in progress

#67 54 coder les get pour l ui
  src/jeu.py
  src/qml/main.qml
  tests/test_jeu.py
Labels: Backend, GUI, Ready for merge

#75 mise a jour carte par réseau
  src/jeu.py
Labels: Ready for merge, bug

#69 appels de fonction de connection au travers de la class Jeu
  src/jeu.py
Labels: Backend, GUI, Ready for merge

#66 64 ajouter un type de case
  src/carte.py
  src/caseattaque.py
  src/navire.py
  tests/test_jeu.py
Labels: Backend, Ready for merge, bug

#76 73 commenter les fonctions
  src/carte.py
  src/case.py
  src/caseattaque.py
  src/jeu.py
  src/navire.py
  src/reseau.py
Labels: documentation, work in progress

#80 ajout du parametre manquant
  src/jeu.py
  src/navire.py
  tests/test_carte.py
  tests/test_jeu.py
Labels: Backend, Ready for merge, bug

#77 finished line
  src/jeu.py
Labels: Backend, GUI, bug

#81 33 placement des navires
  src/carte.py
  src/jeu.py
  src/qml/Attaque/CarteAttaque.qml
  src/qml/Defense/CarteDefense.qml
  src/qml/Defense/CaseDef.qml
  src/qml/Page_connexion/Connexion_Window.qml
  src/qml/Page_connexion/Indication_Connexion.qml
  src/qml/Partie.qml
  src/qml/Placement_navires/Drag_navires.qml
  src/qml/Placement_navires/ModelBateaux.qml
  src/qml/Placement_navires/Placement_navires.qml
  src/qml/main.qml
  tests/test_carte.py
  tests/test_jeu.py
Labels: Backend, GUI, Ready for merge

#89 rotation avec la touche r
  src/qml/Defense/CaseDef.qml
  src/qml/Placement_navires/Drag_navires.qml
Labels: GUI, Ready for merge, bug

#91 Analyse des trames de connexion recues
  src/jeu.py
Labels: Backend, Ready for merge, enhancement

#99 52 detection de la fin de la partie
  src/jeu.py
  src/navire.py
  tests/test_jeu.py
Labels: Backend, Ready for merge, enhancement

#87 82 Mise en place du flow du programme
  src/jeu.py
  src/qml/main.qml
Labels: Backend, GUI, Ready for merge, enhancement

#100 Get ip local
  src/reseau.py
Labels: Backend, Ready for merge, bug

#95 test_impact sur le bateau
  src/carte.py
Labels: Backend, Ready for merge, bug

#94 Liaison QML Python pour tirer
  src/jeu.py
  src/qml/Attaque/CarteAttaque.qml
  src/qml/Attaque/CaseAtt.qml
  src/qml/Defense/CaseDef.qml
  src/qml/Fin_jeu.qml.autosave
  src/qml/Images/defeat.jpg
  src/qml/Page_connexion/Connexion_Window.qml
  src/qml/Partie.qml
  src/qml/Placement_navires/Drag_navires.qml
  src/qml/Placement_navires/Placement_navires.qml
  src/reseau.py
Labels: GUI, Ready for merge

#84 Test position invalide
  src/carte.py
  src/jeu.py
  src/navire.py
  src/qml/Defense/CarteDefense.qml
  src/qml/Defense/CaseDef.qml
  src/qml/Partie.qml
  src/qml/Placement_navires/Drag_navires.qml
  tests/test_carte.py
  tests/test_jeu.py
  tests/test_navire.py
Labels: Backend, Ready for merge, bug

#104 ajout test fin_partie() et fix bug fin_partie()
  src/jeu.py
  tests/test_jeu.py
Labels: Backend, Ready for merge, enhancement

#93 link slot button
  src/jeu.py
  src/main.py
  src/qml/Page_connexion/Connexion_Window.qml
  src/qml/Page_connexion/Heberger.qml
  src/qml/Page_connexion/Rejoindre.qml
  src/reseau.py
Labels: Backend, GUI, Ready for merge

#106 add one digit
  src/qml/Page_connexion/Rejoindre.qml
Labels: GUI, Ready for merge, bug

#108 107 resolution bugs mineurs
  src/jeu.py
  src/qml/Page_connexion/Connexion_Window.qml
  src/qml/main.qml
Labels: Backend, GUI, bug, work in progress

#101 ajout d'informations sur la partie en cours
  src/jeu.py
  src/qml/Attaque/CaseAtt.qml
  src/qml/Fin_jeu.qml
  src/qml/Images/defeat.jpg.xmp
  src/qml/Images/defeat2.jpg
  src/qml/Images/defeat2.jpg.xmp
  src/qml/Images/victoire.jpg
  src/qml/Partie.qml
Labels: GUI, Ready for merge

#110 Send shoot result
  src/carte.py
  src/jeu.py
  tests/test_carte.py
  tests/test_jeu.py
Labels: Backend, Ready for merge, bug
